export const LINKEDIN_WHATSAPP_GROUP_URL = "https://chat.whatsapp.com/LkUAfhwhQJd0cxOOLGX2Az";

export const linkedinInfoSections = [
    {
        title: "Yeni kanalımızı devreye aldık.",
        items: [
            "🚫 Diğer gruplarda bu sistem yok",
            "⚠️ Genelde düzensiz ilerlenir",
            "❌ Gerçek destek sağlanmaz",
            "🚀 Burada fark yaratıyoruz",
            "📊 Daha disiplinli ilerliyoruz",
            "🎯 Bu kanal görünürlük için kuruldu",
            "🤝 Amaç karşılıklı destek sağlamak",
            "👥 Herkes katkı verir",
            "📈 Herkes fayda görür",
            "⚙️ Düzenli ve disiplinli ilerleriz",
            "🔥 İleride detaylar paylaşılacak",
            "⏱️ Zaman limitleri açıklanacak",
            "⚙️ Sistem netleşecek",
            "🧠 Gerçek işleyiş anlatılacak",
            "🙏 Desteğiniz için teşekkürler",
        ],
    },
    {
        title: "hyped.today ile gelişecek sistem",
        items: [
            "🤖 İleride hyped.today ile sistem gelişecek",
            "⚙️ Daha akıllı yapı kurulacak",
            "🚀 Otomasyon devreye alınacak",
        ],
    },
    {
        title: "Gerçek LinkedIn Etkileşim Kuralları",
        items: [
            "🚀 Gerçek LinkedIn Etkileşim Kuralları",
            "🔗 Herkes link paylaşır",
            "📅 Paylaşımlar düzenli yapılır",
            "❤️ Her posta destek verilir",
            "👍 Beğeni zorunlu",
            "💬 Yorum teşvik edilir",
            "⏳ Belirli sürede etkileşim",
            "🚫 Gecikme kabul edilmez",
            "⚠️ Pasif kalan uyarılır",
            "❌ Tekrarında uzaklaştırılır",
            "👤 Takip post sahibinde",
            "🤖 Sistem sonra otomatik",
            "💯 Gerçek destek esastır",
            "🔄 Give to get kuralı",
            "⭐ Kaliteli içerik öncelik",
            "🚫 Spam paylaşım yasak",
            "🧑‍🤝‍🧑 Saygılı iletişim şart",
            "🛡️ Grup disiplini korunur",
            "⚖️ Herkes eşit katkı sağlar",
        ],
    },
] as const;

export const linkedinRuleItems = [
    "🔹 Herkes LinkedIn profil linkini paylaşır",
    "🔹 Grup üyeleri birbirini ekler",
    "🔹 24 saatte sadece 1 link paylaşılır",
    "🔹 Paylaşım süreci planlı ilerler",
    "🔹 24 saat içinde tam destek hedefi",
    "🔹 Her post herkes tarafından etkileşim alır",
    "🔹 Beğeni kontrolü post sahibinde",
    "🔹 24 saat sonra eksikler taglenir",
    "🔹 Destek vermeyenler açık belirtilir",
    "🔹 3 ihlal → 1 hafta uzaklaştırma",
    "🔹 Kurallar herkes için geçerlidir",
    "🔹 Aktif destek verenler ödüllendirilir",
    "🔹 WhatsApp export verileri baz alınır",
    "🔹 Sistem başlangıç aşamasındadır",
    "🔹 1 ay pilot süreç uygulanır",
    "🔹 Sonrasında hyped.today entegrasyonu",
    "🔹 Ek öneriler yarın 18:00’e kadar",
    "🔹 Sonrasında kurallar finalize edilir",
    "🔹 Süreç resmi olarak başlatılır",
] as const;
