-- Storage bucket for project images should be created manually in Supabase Dashboard:
-- Bucket name: project-images
-- Public access: true
--
-- The policy "Public Upload Access" on storage.objects is already applied via Dashboard.
-- If you need to re-apply it, use Supabase SQL Editor:
--
-- CREATE POLICY "Public Upload Access"
-- ON storage.objects FOR INSERT
-- WITH CHECK ( bucket_id = 'project-images' );
